export const ErrorCode = {
  VALIDATION_ERROR:   'VALIDATION_ERROR',
  BAD_REQUEST:        'BAD_REQUEST',
  INVALID_REFERENCE:  'INVALID_REFERENCE',
  UNAUTHORIZED:       'UNAUTHORIZED',
  TOKEN_EXPIRED:      'TOKEN_EXPIRED',
  INVALID_TOKEN:      'INVALID_TOKEN',
  FORBIDDEN:          'FORBIDDEN',
  INSUFFICIENT_ROLE:  'INSUFFICIENT_ROLE',
  NOT_FOUND:          'NOT_FOUND',
  CONFLICT:           'CONFLICT',
  RATE_LIMIT_EXCEEDED:'RATE_LIMIT_EXCEEDED',
  BUDGET_EXCEEDED:    'BUDGET_EXCEEDED',
  PAYLOAD_TOO_LARGE:  'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR:     'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const HTTP_STATUS_ERROR_CODE: Record<number, ErrorCode> = {
  400: ErrorCode.BAD_REQUEST,
  401: ErrorCode.UNAUTHORIZED,
  403: ErrorCode.FORBIDDEN,
  404: ErrorCode.NOT_FOUND,
  409: ErrorCode.CONFLICT,
  422: ErrorCode.VALIDATION_ERROR,
  429: ErrorCode.RATE_LIMIT_EXCEEDED,
  413: ErrorCode.PAYLOAD_TOO_LARGE,
  500: ErrorCode.INTERNAL_ERROR,
};
