apiVersion: v1
kind: Service
metadata:
  name: aihub-web
  namespace: aihub-staging
  labels:
    app.kubernetes.io/name: aihub-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aihub-web
  ports:
    - name: http
      port: 80
      targetPort: http
